### ISSUE TITLE
EB recipes are sometimes wrong

### ISSUE THREAD

**Issue by SimonMeskens** [Katalliaan/Rubedo-Pack#2]
When woggy used old configs, the wrong kind of stone turned into the wrong kind of slabs. Then sockthing had the same issue with brick stairs. This needs to be looked at. See what's consistent and what's not and maybe devise a fix.

**Comment by woggy** [comment]
Slabs are working for me now with the newest version, but brick stairs are still Quite Odd.

**Comment by Katalliaan** [comment]
Can confirm that the stairs recipes are bugged on my end as well.

**Comment by SimonMeskens** [comment]
I fixed this here: 4b97ce39c5d1ba2bf4dbf3c2ee23a8e49e76e4ff
